### ISSUE TITLE
Linux and Mac testing

### ISSUE THREAD

**Issue by altrisi** [altrisi/LogCleaner#1]
It should work perfectly fine, given the Java API is cross-platform, but I'd appreciate some testing just in case.

While no filesystems should consider reading last-access attribute as an access to the file and therefore update it IMO, I'd prefer confirming it's the case so I can add a workaround if it isn't for some system, given if it's updated the simple usage of the mod would refresh the timer of every file at launch.

I believe there's also some filesystems that don't support last access, though those are already handled in the code (we check most recent of creation, modified and last access, and Java returns EPOCH for unsupported attributes according to the doc, giving priority to the other two).

What I like to make sure of is basically that launching the game with the mod doesn't make logs older than 2 weeks get their last access set to this last launch.

**Comment by Aces-and-Jacks** [comment]
Do you still need testing with mac, since the issue is sill open? 

And from what I understand you want to test if logs created 2 weeks ago get deleted by your mod?

**Comment by altrisi** [comment]
My worry is if reading the "last accessed" time may change last access, in which case the mod would never delete anything unless it's been 2 weeks since you opened the game, given I check that to decide if a log should be removed.

And yes help would be appreciated because I haven't got a mac.

**Comment by Aces-and-Jacks** [comment]
Would it be fine if I changed it from 14 days to 2 days? Just so it wouldn't be so long to check if it works. Or did you want me to keep it on 14 days?

**Comment by altrisi** [comment]
Should be the fine, thanks for helping!

**Comment by Aces-and-Jacks** [comment]
So I first launched the instance on the 7th and opened again today the 9th. I looked at the log files tho and they're still there. However maybe it hasn't been exactly 2 days yet so I'll open tomorrow and see if they get deleted

**Comment by Aces-and-Jacks** [comment]
So I set the config for 2 days instead of 14 as I said before on the 7th. opened again now and the logs still show there

**Comment by Aces-and-Jacks** [comment]
would looking at the log to see what the mod did help?

**Comment by Aces-and-Jacks** [comment]
well whether it does or doesn't help I'll post it anyway https://mclo.gs/nfTh8Yv

**Comment by altrisi** [comment]
Oof, I'll have to make a workaround for Mac then, will take a look at some point.

Sorry for the late reply btw, I've been a bit busy lately, but thanks a lot for helping.

**Comment by Aces-and-Jacks** [comment]
no problem. thought i ended up being no help at all and was a bother so glad that wasn't the case

**Comment by altrisi** [comment]
If you have a moment could you try launching [with this build](https://github.com/altrisi/LogCleaner/suites/10104398516/artifacts/492700553) (once) and send the logs again? I added a lot of stuff to the log to be able to know if a possible solution would work (I disabled deleting, just want to know when it changes the thing I'm reading from the log).

The jar with the shortest name in the zip. The source code for it is here if you want it: [`logs` branch](https://github.com/altrisi/LogCleaner/tree/logs).

**Comment by Aces-and-Jacks** [comment]
I'll be able to test it on either Saturday or Sunday

**Comment by altrisi** [comment]
Thanks a lot!

**Comment by Aces-and-Jacks** [comment]
I think I got the right one https://mclo.gs/lE33fQa

**Comment by altrisi** [comment]
Hmmm that's interesting, it looks more like the launcher or something else is the one causing the issue, I'll try to use prism on windows and see if I can find a fix or workaround. Thanks again!

**Comment by altrisi** [comment]
Closing this now as I've also tested linux since creating it and it seems to work
